/****************************************************************************
 * IPSEC Offload framework for Xilinx U25N Accelerator Card.
 * Copyright 2021 Xilinx Inc.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published
 * by the Free Software Foundation, incorporated herein by reference.
 */

#define MC_CMD_IPSEC_DEL_SA_ENC 0x202
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_ENC 12
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_ENC_SC_OFST 0
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_ENC_DC_OFST 4
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_ENC_PROTOCOL_OFST 8

#define MC_CMD_IPSEC_ADD_SA_ENC 0x200
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC 64
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_SC_OFST 0
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_DC_OFST 4
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_PROTOCOL_OFST 8
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_ACTION_FLAG_OFST 12
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_IIV_OFST 20
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_EIV_OFST 24
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_EIV_LEN 8
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_EIV_LBN 96
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_EIV_WIDTH 64
//#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_EIV_MASK_OFST 
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY_OFST 32
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY_LEN 32
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY_LBN 160
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY_WIDTH 256
//#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY_MASK_OFST 24
//#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_KEY 32
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_ENC_SPI_OFST 16

#define MC_CMD_IPSEC_ADD_SA_DEC 0x201
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC 48
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC_SC_OFST 0
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC_SPI_OFST 8
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC_DC_OFST 4
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC_KEY_OFST 16
#define MC_CMD_IPSEC_OFFLOAD_ADD_SA_DEC_IIV_OFST 12

#define MC_CMD_IPSEC_DEL_SA_DEC 0x203
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_DEC 12
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_DEC_SC_OFST 0
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_DEC_SPI_OFST 8
#define MC_CMD_IPSEC_OFFLOAD_DEL_SA_DEC_DC_OFST 4

